### ISSUE TITLE
Question about certificates!

### ISSUE THREAD

**Issue by hazkall** [kellybirr/linkerd2-guide#1]
Hello @kellybirr, I have a question, can I use the same CA certificate for TrustAnchors identity and Webhooks? Or I need to issue different CA certificates. root.linkerd.cluster.local webhook.linkerd.cluster.local Thank you very much

**Comment by kellybirr** [comment]
I used the same for both in my guide and on my clusters.  I don't see the benefit of having them separate.

**Comment by hazkall** [comment]
Thank you !
